// Site fisik + originalFileName (nama file .xlsx asli, dipakai untuk konversi ke Google Sheets)
export const BUILDING_CATEGORIES = [
  "1. BTS Communication Room",
  "12. Draft APAR dan Lightning Protect",
  "2. Signal Building Communication Room",
  "3. Station Building Communication Room",
  "4. SRS Building Communication Room",
  "5. Power Station Communication Room",
  "6. Repeater Communication Room",
  "7. CC & OCE Communication Room",
  "8. CCTV Throat, Emergency Stairs and Bridge",
  "9. Conference Communication Room"
];

export const SITES = [
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K10+200 Base Station 2 (HA-KA 2A&2B _ BTS 2)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat51",
      "cat52",
      "cat18",
      "cat19",
      "cat31",
      "cat32",
      "cat33",
      "cat34",
      "cat04",
      "cat05",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K10+200 Base Station 2 (HA-KA 2A&2B _ BTS 2).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K17+724 Base Station 4 (HA-KA 4 _ BTS 4)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K17+724 Base Station 4 (HA-KA 4 _ BTS 4).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K21+020 Base Station 5 (HA-KA 5 _ BTS 5)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K21+020 Base Station 5 (HA-KA 5 _ BTS 5).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K24+635 Base Station 6 (HA-KA 6 _ BTS 6)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K24+635 Base Station 6 (HA-KA 6 _ BTS 6).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K31+367 Base Station 8 (HA-KA 8 _ BTS 8)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K31+367 Base Station 8 (HA-KA 8 _ BTS 8).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K34+575 Base Station 9 (HA-KA 9 _ BTS 9)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K34+575 Base Station 9 (HA-KA 9 _ BTS 9).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K38+116 Base Station 10 (HA-KA 10 _ BTS 10)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K38+116 Base Station 10 (HA-KA 10 _ BTS 10).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K41+ 683 Base Station Karawang (204)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat27",
      "cat01"
    ],
    "originalFileName": "K41+ 683 Base Station Karawang (204).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K45 + 241 Base Station 11 (KA-PA 1 _ BTS 11)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat42",
      "cat41",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K45 + 241 Base Station 11 (KA-PA 1 _ BTS 11).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K48 + 680 Base Station 12 (KA-PA 2 _ BTS 12)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K48 + 680 Base Station 12 (KA-PA 2 _ BTS 12).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K52 + 083 Base Station 13 (KA-PA 3 _ BTS 13)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K52 + 083 Base Station 13 (KA-PA 3 _ BTS 13).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K59 + 662 Base Station 15 (KA-PA 5 _ BTS 15)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K59 + 662 Base Station 15 (KA-PA 5 _ BTS 15).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K6+352 Base Station 1 (HA-KA 1 _ BTS 1)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat14",
      "cat15",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K6+352 Base Station 1 (HA-KA 1 _ BTS 1).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K63 + 174 Base Station 16 (KA-PA 6 _ BTS 16)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K63 + 174 Base Station 16 (KA-PA 6 _ BTS 16).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K66 + 000 Base Station 17 (KA-PA 7 _ BTS 17)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat51",
      "cat52",
      "cat18",
      "cat19",
      "cat31",
      "cat32",
      "cat33",
      "cat34",
      "cat04",
      "cat05",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K66 + 000 Base Station 17 (KA-PA 7 _ BTS 17).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K73 + 983 Base Station 19 (KA-PA 9 _ BTS 19)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01",
      "cat27"
    ],
    "originalFileName": "K73 + 983 Base Station 19 (KA-PA 9 _ BTS 19).xlsx"
  },
  {
    "buildingCategory": "1. BTS Communication Room",
    "siteName": "K80 + 835 Base Station 20 (KA-PA 10 _ BTS 20)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat27",
      "cat01"
    ],
    "originalFileName": "K80 + 835 Base Station 20 (KA-PA 10 _ BTS 20).xlsx"
  },
  {
    "buildingCategory": "12. Draft APAR dan Lightning Protect",
    "siteName": "Lembar Pemeriksaan APAR 2026",
    "categoryIds": [
      "cat02"
    ],
    "originalFileName": "Lembar Pemeriksaan APAR 2026.xlsx"
  },
  {
    "buildingCategory": "12. Draft APAR dan Lightning Protect",
    "siteName": "Lembar Pemeriksaan Lightning Protection 2026",
    "categoryIds": [
      "cat36"
    ],
    "originalFileName": "Lembar Pemeriksaan Lightning Protection 2026.xlsx"
  },
  {
    "buildingCategory": "2. Signal Building Communication Room",
    "siteName": "K0+316 Halim Signal Building Communication (101)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat50",
      "cat49",
      "cat20",
      "cat23",
      "cat43",
      "cat44",
      "cat38",
      "cat55",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat03",
      "cat41",
      "cat39",
      "cat42",
      "cat40",
      "cat46",
      "cat47",
      "cat27",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K0+316 Halim Signal Building Communication (101).xlsx"
  },
  {
    "buildingCategory": "2. Signal Building Communication Room",
    "siteName": "K41+607 Karawang Signal Building Communication (202)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat50",
      "cat49",
      "cat23",
      "cat44",
      "cat43",
      "cat38",
      "cat55",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K41+607 Karawang Signal Building Communication (202).xlsx"
  },
  {
    "buildingCategory": "3. Station Building Communication Room",
    "siteName": "K41+475 Karawang Station Building Communication (201)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat29",
      "cat30",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K41+475 Karawang Station Building Communication (201).xlsx"
  },
  {
    "buildingCategory": "4. SRS Building Communication Room",
    "siteName": "K14+276 Signal Relay Station 1 (HA-KA 3 _ BTS 3)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K14+276 Signal Relay Station 1 (HA-KA 3 _ BTS 3).xlsx"
  },
  {
    "buildingCategory": "4. SRS Building Communication Room",
    "siteName": "K27+985 Signal Relay Station 2 (HA-KA 7 _ BTS 7)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K27+985 Signal Relay Station 2 (HA-KA 7 _ BTS 7).xlsx"
  },
  {
    "buildingCategory": "4. SRS Building Communication Room",
    "siteName": "K56 + 096 Signal Relay Station 3 (KA-PA 4 _ BTS 14)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K56 + 096 Signal Relay Station 3 (KA-PA 4 _ BTS 14).xlsx"
  },
  {
    "buildingCategory": "4. SRS Building Communication Room",
    "siteName": "K70 + 090 Signal Relay Station 4 (KA-PA 8 _ BTS 18)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat51",
      "cat52",
      "cat18",
      "cat19",
      "cat31",
      "cat32",
      "cat33",
      "cat34",
      "cat04",
      "cat05",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat46",
      "cat47",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K70 + 090 Signal Relay Station 4 (KA-PA 8 _ BTS 18).xlsx"
  },
  {
    "buildingCategory": "4. SRS Building Communication Room",
    "siteName": "K83 + 834 Signal Relay Station 5 (KA-PA 11 _ BTS 21)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat03",
      "cat39",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat42",
      "cat40",
      "cat46",
      "cat47",
      "cat21",
      "cat01",
      "cat27"
    ],
    "originalFileName": "K83 + 834 Signal Relay Station 5 (KA-PA 11 _ BTS 21).xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K0+215 - Halim 20KV Substation (Dormitory)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K0+215 - Halim 20KV Substation (Dormitory).xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K1+267 - AT Post 1",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K1+267 - AT Post 1.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K12+075 - Halim 150KV Substation",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K12+075 - Halim 150KV Substation.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K22+025 - AT Post 2",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K22+025 - AT Post 2.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K32+475 - Section Post 1",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K32+475 - Section Post 1.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K41+676 - Karawang 20KV Substation (203)",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K41+676 - Karawang 20KV Substation (203).xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K42 + 365 AT Post 3",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K42 + 365 AT Post 3.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K56 + 665 - Karawang 150KV Substation",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K56 + 665 - Karawang 150KV Substation.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K67 + 965 - AT Post 4",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K67 + 965 - AT Post 4.xlsx"
  },
  {
    "buildingCategory": "5. Power Station Communication Room",
    "siteName": "K79 + 865 - Section Post 2",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat48",
      "cat44",
      "cat18",
      "cat19",
      "cat29",
      "cat30",
      "cat53",
      "cat54",
      "cat08",
      "cat09",
      "cat10",
      "cat11",
      "cat12",
      "cat13",
      "cat41",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K79 + 865 - Section Post 2.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K2+075 Repeater Inlet Tunnel 1",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat28",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K2+075 Repeater Inlet Tunnel 1.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K3+075 Repeater Inside Tunnel 1",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K3+075 Repeater Inside Tunnel 1.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K4+ Repeater Outlet Tunnel 1",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat28",
      "cat21",
      "cat01"
    ],
    "originalFileName": "K4+ Repeater Outlet Tunnel 1.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K74 + 439 Repeater Inlet Tunnel 2",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K74 + 439 Repeater Inlet Tunnel 2.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K75 + 500 Repeater OutletTunnel 2",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K75 + 500 Repeater OutletTunnel 2.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K76 + 000 Repeater Inlet Tunnel 3",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K76 + 000 Repeater Inlet Tunnel 3.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K76 + 722 Repeater Outlet Tunnel 3",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K76 + 722 Repeater Outlet Tunnel 3.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K77 + 350 Repeater Inlet Tunnel 4",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K77 + 350 Repeater Inlet Tunnel 4.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K78 + 662 Repeater Outlet Tunnel 4",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K78 + 662 Repeater Outlet Tunnel 4.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K82 + 372 Repeater Inlet Tunnel 5",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K82 + 372 Repeater Inlet Tunnel 5.xlsx"
  },
  {
    "buildingCategory": "6. Repeater Communication Room",
    "siteName": "K82 + 540 Repeater Outlet Tunnel 5",
    "categoryIds": [
      "cat37",
      "cat35",
      "cat18",
      "cat19",
      "cat39",
      "cat53",
      "cat54",
      "cat16",
      "cat17",
      "cat40",
      "cat21",
      "cat01",
      "cat28"
    ],
    "originalFileName": "K82 + 540 Repeater Outlet Tunnel 5.xlsx"
  },
  {
    "buildingCategory": "7. CC & OCE Communication Room",
    "siteName": "Halim - Comprehensive Controller Room (CC)",
    "categoryIds": [
      "cat45",
      "cat44",
      "cat24",
      "cat25"
    ],
    "originalFileName": "Halim - Comprehensive Controller Room (CC).xlsx"
  },
  {
    "buildingCategory": "7. CC & OCE Communication Room",
    "siteName": "Halim - On Call Emergency Room (OCE)",
    "categoryIds": [
      "cat45",
      "cat44",
      "cat24",
      "cat25"
    ],
    "originalFileName": "Halim - On Call Emergency Room (OCE).xlsx"
  },
  {
    "buildingCategory": "7. CC & OCE Communication Room",
    "siteName": "Karawang - Comprehensive Controller Room (CC)",
    "categoryIds": [
      "cat45",
      "cat44",
      "cat24",
      "cat25"
    ],
    "originalFileName": "Karawang - Comprehensive Controller Room (CC).xlsx"
  },
  {
    "buildingCategory": "7. CC & OCE Communication Room",
    "siteName": "Karawang - On Call Emergency Room (OCE)",
    "categoryIds": [
      "cat45",
      "cat44",
      "cat24",
      "cat25"
    ],
    "originalFileName": "Karawang - On Call Emergency Room (OCE).xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "CCTV Crossway Bridge K4 + 871",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "CCTV Crossway Bridge K4 + 871.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "CCTV Crossway Bridge K53",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "CCTV Crossway Bridge K53.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "CCTV Throat Area Stasiun Halim",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "CCTV Throat Area Stasiun Halim.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "CCTV Throat Area Stasiun Karawang",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "CCTV Throat Area Stasiun Karawang.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K10 + 799",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K10 + 799.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K13 + 724",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K13 + 724.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K16 + 638",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K16 + 638.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K19 + 509",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K19 + 509.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K22 + 802",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K22 + 802.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K25 + 725 ",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K25 + 725 .xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K29 + 043",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K29 + 043.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K32 + 072",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K32 + 072.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K34 + 898 ",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K34 + 898 .xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K37 + 827",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K37 + 827.xlsx"
  },
  {
    "buildingCategory": "8. CCTV Throat, Emergency Stairs and Bridge",
    "siteName": "Video Poll CCTV Tangga Darurat K7 + 742",
    "categoryIds": [
      "cat35",
      "cat18",
      "cat19"
    ],
    "originalFileName": "Video Poll CCTV Tangga Darurat K7 + 742.xlsx"
  },
  {
    "buildingCategory": "9. Conference Communication Room",
    "siteName": "K0+316 Conference Room Stasiun Halim",
    "categoryIds": [
      "cat22"
    ],
    "originalFileName": "K0+316 Conference Room Stasiun Halim.xlsx"
  },
  {
    "buildingCategory": "9. Conference Communication Room",
    "siteName": "K41+475 Conference Room Stasiun Karawang",
    "categoryIds": [
      "cat22"
    ],
    "originalFileName": "K41+475 Conference Room Stasiun Karawang.xlsx"
  }
];
